"""create initial schema

Revision ID: 20260715_0001
Revises:
Create Date: 2026-07-20 22:24:16.272433

"""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20260715_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # vector 是 PostgreSQL 扩展，必须先安装，然后才能创建 vector(512) 列。
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("employee_id", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("manager_id", sa.String(length=30), nullable=True),
        sa.Column("roles", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["employees.employee_id"],
            name=op.f("fk_employees_manager_id_employees"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("employee_id", name=op.f("pk_employees")),
    )
    op.create_index(op.f("ix_employees_department"), "employees", ["department"], unique=False)
    op.create_table(
        "policy_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_code", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_chunks")),
        sa.UniqueConstraint(
            "policy_code", "chunk_index", name=op.f("uq_policy_chunks_policy_code")
        ),
    )
    op.create_index(
        op.f("ix_policy_chunks_policy_code"), "policy_chunks", ["policy_code"], unique=False
    )
    op.create_table(
        "systems",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_systems")),
        sa.UniqueConstraint("name", name=op.f("uq_systems_name")),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("draft", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fault_mode", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_index(op.f("ix_workspaces_token_hash"), "workspaces", ["token_hash"], unique=True)
    op.create_table(
        "entitlements",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("system_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("approval_policy", sa.String(length=50), nullable=False),
        sa.Column("owner_id", sa.String(length=30), nullable=True),
        sa.Column("self_service_allowed", sa.Boolean(), nullable=False),
        sa.Column("eligible_departments", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("eligible_roles", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("max_duration_days", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["employees.employee_id"],
            name=op.f("fk_entitlements_owner_id_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["system_code"],
            ["systems.code"],
            name=op.f("fk_entitlements_system_code_systems"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_entitlements")),
    )
    op.create_index(
        op.f("ix_entitlements_system_code"), "entitlements", ["system_code"], unique=False
    )
    op.create_table(
        "access_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.String(length=30), nullable=False),
        sa.Column("entitlement_code", sa.String(length=100), nullable=False),
        sa.Column("project_code", sa.String(length=100), nullable=False),
        sa.Column("data_scope", sa.Text(), nullable=False),
        sa.Column("business_reason", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("request_status", sa.String(length=40), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "duration_days > 0", name=op.f("ck_access_requests_duration_days_positive")
        ),
        sa.ForeignKeyConstraint(
            ["entitlement_code"],
            ["entitlements.code"],
            name=op.f("fk_access_requests_entitlement_code_entitlements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["employees.employee_id"],
            name=op.f("fk_access_requests_requester_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_access_requests_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_requests")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_access_requests_workspace_id")),
    )
    op.create_index(
        op.f("ix_access_requests_workspace_id"), "access_requests", ["workspace_id"], unique=False
    )
    op.create_table(
        "access_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "expires_at > starts_at", name=op.f("ck_access_grants_valid_time_range")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "request_id"],
            ["access_requests.workspace_id", "access_requests.id"],
            name=op.f("fk_access_grants_workspace_id_access_requests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_access_grants_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_grants")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_access_grants_idempotency_key")),
        sa.UniqueConstraint("request_id", name=op.f("uq_access_grants_request_id")),
    )
    op.create_index(
        op.f("ix_access_grants_workspace_id"), "access_grants", ["workspace_id"], unique=False
    )
    op.create_table(
        "approval_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("approval_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "request_id"],
            ["access_requests.workspace_id", "access_requests.id"],
            name=op.f("fk_approval_cases_workspace_id_access_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_approval_cases_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_cases")),
        sa.UniqueConstraint("request_id", name=op.f("uq_approval_cases_request_id")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_approval_cases_workspace_id")),
    )
    op.create_index(
        op.f("ix_approval_cases_workspace_id"), "approval_cases", ["workspace_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id", "request_id"],
            ["access_requests.workspace_id", "access_requests.id"],
            name=op.f("fk_audit_events_workspace_id_access_requests"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_audit_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_workspace_id"), "audit_events", ["workspace_id"], unique=False
    )
    op.create_table(
        "approval_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("approval_case_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("approver_id", sa.String(length=30), nullable=False),
        sa.Column("approver_role", sa.String(length=50), nullable=False),
        sa.Column("step_status", sa.String(length=30), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("step_order > 0", name=op.f("ck_approval_steps_step_order_positive")),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["employees.employee_id"],
            name=op.f("fk_approval_steps_approver_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "approval_case_id"],
            ["approval_cases.workspace_id", "approval_cases.id"],
            name=op.f("fk_approval_steps_workspace_id_approval_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_approval_steps_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_steps")),
        sa.UniqueConstraint(
            "approval_case_id", "step_order", name=op.f("uq_approval_steps_approval_case_id")
        ),
    )
    op.create_index(
        op.f("ix_approval_steps_approval_case_id"),
        "approval_steps",
        ["approval_case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_steps_workspace_id"), "approval_steps", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approval_steps_workspace_id"), table_name="approval_steps")
    op.drop_index(op.f("ix_approval_steps_approval_case_id"), table_name="approval_steps")
    op.drop_table("approval_steps")
    op.drop_index(op.f("ix_audit_events_workspace_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_approval_cases_workspace_id"), table_name="approval_cases")
    op.drop_table("approval_cases")
    op.drop_index(op.f("ix_access_grants_workspace_id"), table_name="access_grants")
    op.drop_table("access_grants")
    op.drop_index(op.f("ix_access_requests_workspace_id"), table_name="access_requests")
    op.drop_table("access_requests")
    op.drop_index(op.f("ix_entitlements_system_code"), table_name="entitlements")
    op.drop_table("entitlements")
    op.drop_index(op.f("ix_workspaces_token_hash"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_table("systems")
    op.drop_index(op.f("ix_policy_chunks_policy_code"), table_name="policy_chunks")
    op.drop_table("policy_chunks")
    op.drop_index(op.f("ix_employees_department"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
    # 所有使用 vector 类型的表删除后，才能移除扩展。
    op.execute("DROP EXTENSION IF EXISTS vector")
